version: "3"
   
services:

  postgres:
    container_name: postgres_api
    image: postgres:13.0
    environment:
      - POSTGRES_NAME = postgres
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres

  django:
    container_name: django_api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
